# Generated by Django 3.0.4 on 2020-03-13 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('year_in_university', models.CharField(choices=[('Undergraduate', (('UNDERGRAD_1YEAR', 'Undergraduate (year 1)'), ('UNDERGRAD_2YEAR', 'Undergraduate (year 2)'), ('UNDERGRAD_3YEAR', 'Undergraduate (year 3)'), ('UNDERGRAD_4YEAR', 'Undergraduate (year 4)'))), ('Postgraduate', (('POSTGRAD', 'Postgraduate'),))], max_length=32)),
                ('overall_rating', models.IntegerField(default=0)),
                ('lecturer_rating', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('informative', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UofGStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('current_student', models.BooleanField()),
                ('year_of_studies', models.CharField(choices=[('Undergraduate', (('UNDERGRAD_1YEAR', 'Undergraduate (year 1)'), ('UNDERGRAD_2YEAR', 'Undergraduate (year 2)'), ('UNDERGRAD_3YEAR', 'Undergraduate (year 3)'), ('UNDERGRAD_4YEAR', 'Undergraduate (year 4)'))), ('Postgraduate', (('POSTGRAD', 'Postgraduate'),))], max_length=32)),
                ('contact', models.BooleanField()),
                ('courses', models.ManyToManyField(to='csapp.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('current_student', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(default=0)),
                ('lecturer_rating', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('informative', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapp.UofGStudent')),
            ],
        ),
    ]
