# Generated by Django 2.2.3 on 2020-03-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='course',
            name='informative',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overall_rating',
        ),
    ]
