# Generated by Django 2.2.3 on 2020-03-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0002_courserating_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserating',
            name='name',
        ),
    ]
