# Generated by Django 2.2.3 on 2020-03-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0003_remove_courserating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='course_rating',
        ),
        migrations.DeleteModel(
            name='CourseRating',
        ),
        migrations.DeleteModel(
            name='courseReview',
        ),
    ]
