# Generated by Django 2.2.3 on 2020-03-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0004_auto_20200314_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name': 'Course Rating', 'verbose_name_plural': 'Course Ratings'},
        ),
        migrations.AlterModelOptions(
            name='nonstudent',
            options={'verbose_name': 'Non student', 'verbose_name_plural': 'Non Students'},
        ),
        migrations.AlterModelOptions(
            name='uofgstudent',
            options={'verbose_name': 'UofG Student', 'verbose_name_plural': 'Uofg Students'},
        ),
    ]
