# Generated by Django 2.2.3 on 2020-03-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0005_courserating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
