# Generated by Django 2.2.3 on 2020-03-12 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0006_delete_courserating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('lecturer_rating', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('engagement', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('informative', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapp.Course')),
            ],
        ),
    ]
