# Generated by Django 2.2.3 on 2020-03-12 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csapp', '0008_auto_20200312_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='UofGStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('current_student', models.BooleanField()),
                ('year_of_studies', models.CharField(choices=[('Undergraduate', (('UNDERGRAD_1YEAR', 'Undergraduate (year 1)'), ('UNDERGRAD_2YEAR', 'Undergraduate (year 2)'), ('UNDERGRAD_3YEAR', 'Undergraduate (year 3)'), ('UNDERGRAD_1YEAR', 'Undergraduate (year 4)'))), ('Postgraduate', (('POSTGRAD', 'Postgraduate'),))], max_length=32)),
                ('contact', models.BooleanField()),
                ('courses', models.ManyToManyField(to='csapp.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('current_student', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('lecturer_rating', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('engagement', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('informative', models.CharField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')], max_length=15)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapp.UofGStudent')),
            ],
        ),
    ]
