# Generated by Django 2.2.3 on 2020-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0009_courserating_nonstudent_uofgstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_in_university',
            field=models.CharField(choices=[('Undergraduate', (('UNDERGRAD_1YEAR', 'Undergraduate (year 1)'), ('UNDERGRAD_2YEAR', 'Undergraduate (year 2)'), ('UNDERGRAD_3YEAR', 'Undergraduate (year 3)'), ('UNDERGRAD_4YEAR', 'Undergraduate (year 4)'))), ('Postgraduate', (('POSTGRAD', 'Postgraduate'),))], max_length=32),
        ),
        migrations.AlterField(
            model_name='uofgstudent',
            name='year_of_studies',
            field=models.CharField(choices=[('Undergraduate', (('UNDERGRAD_1YEAR', 'Undergraduate (year 1)'), ('UNDERGRAD_2YEAR', 'Undergraduate (year 2)'), ('UNDERGRAD_3YEAR', 'Undergraduate (year 3)'), ('UNDERGRAD_4YEAR', 'Undergraduate (year 4)'))), ('Postgraduate', (('POSTGRAD', 'Postgraduate'),))], max_length=32),
        ),
    ]
