# Generated by Django 2.2.3 on 2020-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0012_auto_20200312_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='informative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='overall_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='informative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='lecturer_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='overall_rating',
            field=models.IntegerField(default=0),
        ),
    ]
