import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE','rate_my_cs_course.settings')

import django
django.setup()
from django.contrib.auth.models import User
from csapp.models import *

def populate():
    undergraduate_1year_courses = [
        {'name': '1CT INTRODUCTION TO COMPUTATIONAL THINKING COMPSCI1016', 
        'description': 'Computational processes are increasingly being discovered in natural, social and economic systems as well as typical silicon-based computing devices such as laptops and smartphones. For those with little or no previous computing education, this course develops the necessary understanding and thinking skills so that such systems can be viewed as predictable, understandable and ultimately controllable. It is valuable in its own right, as an underpinning now required in many other disciplines, and as a foundation for further study in Computing Science.',
        'year_in_university': 1,
        'views' : 5},
        {'name': '1S SYSTEMS COMPSCI1018', 
        'description': 'CS1S introduces the fundamentals of computer systems, including representation of information, digital circuits, processor organisation, machine language, and the relation between hardware and software systems.',
        'year_in_university': 1,
        'views' : 4},
        {'name':'1F - COMPUTING FUNDAMENTALS COMPSCI1006',
        'description':'The aim of the CS1F course is to give students an understanding of human-computer interaction (styles of interaction, requirements for an interactive system in relation to the nature of the tasks being supported, issues in the design of interactive systems, critical assessment of designs); the ways in which databases contribute to the management of large amounts of data, the professional and ethical issues raised by the existence of databases and networks.',
        'year_in_university': 1,
        'views' : 2},
        {'name':'COMPUTING SCIENCE 1P (STANDARD ROUTE) COMPSCI1001',
        'description':'The CS1P course is designed for students with good foundational computational thinking skills - that is, a solid understanding of basic programming concepts and the ability to solve simple unseen programming problems from scratch with no assistance. The course reviews this foundation and then builds on it by developing students ability to reason about elements of the software development process, including for example, complexity of algorithms, rigorous testing techniques and problem solving methodologies.',
        'year_in_university': 1,
        'views' : 10},
        {'name':'COMPUTING SCIENCE 1P (HALF COURSE) COMPSCI1005',
        'description':'The aim of the CS1P (Half) course is to produce programmers equipped with an understanding of: Fundamental computational concepts underlying most programming languages; A range of problem-solving techniques using computers; The skills supporting the solution of small problems using a programming language; The clear expression of solutions at different levels of abstraction.',
        'year_in_university': 1},
        {'name':'COMPUTING SCIENCE 1PX (ALTERNATE ROUTE) COMPSCI1017',
        'description':'This course assumes core computational thinking skills and is designed to be a natural follow-on from the CS1CT course for those who decide they wish to continue their study of Computing Science. The course develops students ability to reason about elements of the software development process, including for example, complexity of algorithms, rigorous testing techniques and problem solving methodologies.',
        'year_in_university': 1},
        {'name':'FOUNDATIONS OF PROFESSIONAL SOFTWARE ENGINEERING COMPSCI1019',
        'description':'Students on the GA programme will be going straight into a working environment, so it is important that they understand the fundamentals of working as a professional. This course will introduce them to many facets of software development beyond simply writing code, which will be important to prepare them for professional work.',
        'year_in_university': 1},
        {'name':'HOW TO LEARN A NEW LANGUAGE COMPSCI1020',
        'description':'After this course students will be able to learn new programming languages themselves. It is designed to teach the fundamentals of programming in such a way that students will very easily be able to pick up new languages and be able to use them quickly in their respective workplaces. Glasgow graduates are good at picking up new languages quickly - we want to distil this skill into a single course without teaching specific languages.',
        'year_in_university':1},
        {'name':'PRACTICAL ALGORITHMS COMPSCI1021',
        'description':'This course is designed to impart a breadth of knowledge on data structures, particularly with respect to the mathematical foundations involved in manipulating them. In doing so, it will also introduce students to foundational mathematical concepts in computing that will help them to better understand efficient programming and will provide a basis on which to build more complex mathematical concepts in later years of study.',
        'year_in_university':1},
        {'name':'SPATIAL SKILLS TRAINING 1 COMPSCI1026',
        'description':'This course is designed to develop the spatial skills of participants.',
        'year_in_university':1},
        {'name':'TESTING AND SOFTWARE IMPROVEMENT COMPSCI1022',
        'description':'Students taking this course will know how to write code in a given language. The purpose of this course is to improve the quality of their code, bringing it up to a professional standard with considerations for testing, efficiency and readability.',
        'year_in_university':1},
        {'name':'WEB APPLICATION SYSTEMS COMPSCI1023',
        'description':'This course will introduce students to web application design and the underlying networking concepts which web applications and services rely on.',
        'year_in_university':1},
        {'name':'WORKPLACE ASSESSMENT YEAR 1 COMPSCI1024',
        'description':'Students will have three uninterrupted months in the workplace to be involved in real projects as part of a team. During this time, they should develop a portfolio of work which they have contributed to, which should detail concepts covered in the academic year. This course, and the equivalent courses in each year of the programme, is intended to create reflective life-long learners.',
        'year_in_university':1}
    ]
    undergraduate_2year_courses = [    
        {'name':'ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
        'description':'To introduce the foundational mathematics needed for Computing Science; To make students proficient in their use; To show how they can be applied to advantage in understanding computational phenomena.',
        'year_in_university': 2},
        {'name':'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
        'description':'To familiarise students with fundamental data types and data structures used in programming, with the design and analysis of algorithms for the manipulation of such structures, and to provide practice in the implementation and use of these structures and algorithms in a Java context.',
        'year_in_university':2},
        {'name':'JAVA PROGRAMMING 2 COMPSCI2001',
        'description':'This course extends students experience in programming using a strongly typed language (Java) and strengthens their problem solving skills. Students will learn the ideas that underpin object-oriented programming and will apply those concepts in developing small and medium sized software systems. Students will also learn to select and re-use existing software components and libraries, and will gain experience in concurrent programming and elementary graphical user-interface (GUI) development.',
        'year_in_university':2},
        {'name':'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
        'description':'The course will introduce students to essential topics in computer networks and operating systems. It has a focus on the underlying concepts, design, and operation of the Internet, and on the role, basic features, and principles of computer operating systems.',
        'year_in_university':2},
        {'name':'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
        'description':'This course introduces the basic concepts of software engineering. Students will learn methods for the design, implementation, testing and documentation of larger object-oriented programs, and will also develop program comprehension and design skills by studying and extending existing programs.',
        'year_in_university':2},
        {'name':'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021',
        'description':'The aim of this course is to provide students with a comprehensive overview of web application development. It will provide students with the skills to design and develop distributed web applications in a disciplined manner, using a range of tools and technologies. It will also strengthen their understanding of the context and rationale of distributed systems. ',
        'year_in_university':2}
    ]
    undergraduate_3year_courses = [
        {'name':'SOFTWARE ENGINEERING M3 COMPSCI3005',
        'description':'An introduction to software engineering principles, processes and techniques.',
        'year_in_university':3},
        {'name':'TEAM PROJECT 3 COMPSCI3004',
        'description':'This course gives students the experience of working on a substantial team based software project. The course provides the opportunity to apply the principles, practices and tools learned during the associated Professional Software Development (H) course.',
        'year_in_university':3}
    ]
    undergraduate_4year_courses = [
        {'name':'ADVANCED NETWORKED SYSTEMS (H) COMPSCI4083',
        'description':'The course aims to give students a deep understanding of the fundamental design, implementation, management, and evaluation principles that govern large-scale, high-speed networked systems. These include algorithmic and implementation techniques for high-speed networking in routers and end-nodes; systems performance measurement and modelling principles; network and system resource management, allocation and engineering schemes; and research and technological advances that drive the development of a converged, global telecommunications medium of the future.',
        'year_in_university':4},
        {'name':'ADVANCED NETWORKING AND COMMUNICATIONS (H) COMPSCI4002',
        'description':'This course adds depth and some breadth to the material covered in Networked Systems (H). Advanced Networking and Communications (H) will show how fundamental principles of communications theory underpin the structures of the global telecommunications network and the Internet and determine the logic of how these networks interact.',
        'year_in_university':4},
        {'name':'ADVANCED SOFTWARE ENGINEERING PRACTICES (H) COMPSCI4071',
        'description':'This course gives students the opportunity to learn and practice advanced principles, methods and tools in Software Engineering.  The course is intended for students who have experience of software development through a summer internship or similar. The course covers technical and management skills that are needed for mentoring and leading teams of software developers. The course is delivered in collaboration with an established software industry partner (JP Morgan).',
        'year_in_university':4},
        {'name':'ALGORITHMICS I (H) COMPSCI4009',
        'description':'To develop the students skills in the design and analysis of algorithms; To study algorithms for a range of important standard problems; To introduce the student to the theory of NP-completeness together with its practical implications;To make the student aware of fundamental concepts of computability.',
        'year_in_university':4},
        {'name':'ALGORITHMICS II (H) COMPSCI4003',
        'description':'The aims of the course are: To present a broad range of algorithm design methods, with examples chosen to reflect practical applications; To enable students to make educated choices between strategies for algorithmic problem-solving;To convey the significance of computational complexity, and to present a range of methods for dealing with it in practice.',
        'year_in_university':4},
        {'name':'ARTIFICIAL INTELLIGENCE (H) COMPSCI4004',
        'description':'Artificial Intelligence (H) is an introduction to Artificial Intelligence, giving the students an overview of intelligent agent design.',
        'year_in_university':4},
        {'name':'BIG DATA: SYSTEMS, PROGRAMMING, AND MANAGEMENT (H) COMPSCI4064',
        'description':'Big Data is nowadays manifested in a very large number of environments and application fields pertaining to our education, entertainment, health, public governance, enterprising, etc. The course will endow students with the understanding of the new challenges big data introduces and the currently available solutions. These include (i) challenges pertaining to the modelling, accessing, and storing of big data, (ii) an understanding of the fundamentals of systems designed to store and access big data, and (iii) programming paradigms for efficient scalable access to big data.',
        'year_in_university':4},
        {'name':'BIG DATA: SYSTEMS, PROGRAMMING, AND MANAGEMENT (SIT) SIT4039',
        'description':'Big Data is nowadays manifested in a very large number of environments and application fields pertaining to our education, entertainment, health, public governance, enterprising, etc. The course will endow students with the understanding of the new challenges big data introduces and the currently available solutions. These include (i) challenges pertaining to the modelling, accessing, and storing of big data, (ii) an understanding of the fundamentals of systems designed to store and access big data, and (iii) programming paradigms for efficient scalable access to big data.',
        'year_in_university':4},
        {'name':'COMPUTATIONAL SOCIAL INTELLIGENCE (H) COMPSCI4080',
        'description':'The course introduces the core methodologies behind automatic approaches aimed at making sense of social and psychological aspects of human behaviour. In particular, the course shows 1) how to design and organise the observation of human behaviour in view of the application of automatic approaches, 2) how to apply psychometric instruments for the quantitative analysis of social and psychological phenomena, and 3) how to apply basic statistical techniques to human behaviour analysis and understanding. The course is interdisciplinary and it requires the acquisition of both computing and social psychological notions. The application areas to which the course is relevant include, e.g., social robotics, user experience analysis, social media analytics, surveillance and e-health (the list is not exhaustive).',
        'year_in_university':4},
        {'name':'COMPUTER ARCHITECTURE (H) COMPSCI4007',
        'description':'The course explains in depth how a computer works, by developing a digital circuit that implements an instruction set architecture. Topics include cache, virtual memory, support by the architecture for the operating system, and instruction level parallelism.',
        'year_in_university':4},
        {'name':'COMPUTER VISION METHODS AND APPLICATIONS (H) COMPSCI4066',
        'description':'The Computer Vision Methods and Applications (CVMA) course is intended to equip students with the necessary theoretical and practical understanding of image processing and computer vision techniques to enable them to meet the challenges of building advanced image-based applications. Examples of potential vision-based applications include: image understanding in mobile devices (cameras, phones, tablet computers etc.), robot vision systems, autonomous vehicle guidance and road monitoring, driver attention monitoring, image database query systems, creative media production tools, interactive gaming, augmented reality and visual biometrics, forensic image analysis, security and surveillance, and medical imaging. The course will focus on the application of recent advances in Computer Vision techniques that underpin a wide variety of systems and products based on methods such as: face detection, object recognition, tracking, segmentation and 3D imaging.',
        'year_in_university':4},
        {'name':'COMPUTING SCIENCE IN THE CLASSROOM (H) COMPSCI4017',
        'description':'This course aims to develop in students a better understanding of and confidence in Computing Science/Software Engineering as a subject; provide students with an awareness and experience of operating as a teacher and facilitator in a school environment; enable students to develop a set of key transferable skills such as reflecting on critical incidents, analysis, developing coherent arguments, communication, planning and so on; promote better relations between schools and university computing; heighten pupils awareness of the many forms of computing, including its forms as academic discipline (computing science), distinctive profession (software engineering) and as a ubiquitous family of skills (ICT).',
        'year_in_university':4},
        {'name':'CYBER SECURITY FUNDAMENTALS (H) COMPSCI4062',
        'description':'This course provides an introduction to the foundational aspects of computer security, such as algorithms and protocols. It also covers ways in which these systems can be attacked and techniques for thwarting these attacks.',
        'year_in_university':4},
        {'name':'CYBER SECURITY FUNDAMENTALS (SIT) SIT4023',
        'description':'This course provides an introduction to the foundational aspects of computer security, such as algorithms and protocols. It also covers ways in which these systems can be attacked and techniques for thwarting these attacks.',
        'year_in_university':4},
        {'name':'DATA FUNDAMENTALS (H) COMPSCI4073',
        'description':'This course will cover computational approaches to working with numerical data on a large scale. Computation on arrays of continuous variables underpins machine learning, information retrieval, data analytics, computer vision and signal processing. This course will cover vectorised operations on numerical arrays, fundamental stochastic and probabilistic methods and scientific visualisation.',
        'year_in_university':4},
        {'name':'DATABASE SYSTEMS (H) COMPSCI4013',
        'description':'From the basic skills derived in CS1F, to develop the software engineering and database administration skills required for designing, creating, running and developing a relational database application and its associated application software suite. Understanding of how conventional programming languages (e.g., Java/JDBC) interact with databases; Understanding of the fundamental concepts, functional dependency and normalization theories and methods of the relational data model; Understanding the principles of database indexing, file structures, hash-based file structures, tree-based indexes; Understanding the cost-based query optimization methods; Understanding the principles of selection selectivity and joint selectivity using histograms in query optimization; Introduction to data analytics tasks and advanced methods & techniques.',
        'year_in_university':4},
        {'name':'DISTRIBUTED ALGORITHMS AND SYSTEMS (SIT) SIT4024',
        'description':'Distributed systems are ubiquitous in commerce and industry, from the international banking network to process control in large industrial sites. This course builds on the introductions to operating systems and networked systems in level 3, specifically focussing on the software engineering issues raised by distributed systems and algorithms for use in distributed systems.The key feature of this course will be the assumption that a distributed system is one in which: partial failure is to be expected; local and remote operations differ greatly in cost; and an element of message passing is required for communication.',
        'year_in_university':4},
        {'name':'DISTRIBUTED AND PARALLEL TECHNOLOGIES (H) COMPSCI4082',
        'description':'This course aims to develop in students a better understanding of the computing science challenges posed by the dominant highly concurrent architectures. These include engineering scalable and reliable systems. Students will gain both a broad overview of emerging technologies for engineering reliable and scalable systems, together with practical experience using a small number of key technologies for designing, implementing and evaluating scalable parallel systems and reliable distributed systems.',
        'year_in_university':4},
        {'name':'FUNCTIONAL PROGRAMMING (H) COMPSCI4021',
        'description':'Functional programming is introduced using Haskell. The standard programming techniques, as well as some advanced topics, are covered and applied to realistic programming problems.',
        'year_in_university':4},
        {'name':'FUNCTIONAL PROGRAMMING (SIT) SIT4058',
        'description':'Functional programming is introduced using Haskell. The standard programming techniques, as well as some advanced topics, are covered and applied to realistic programming problems.',
        'year_in_university':4},
        {'name':'HUMAN-COMPUTER INTERACTION (H) COMPSCI4023',
        'description':'The aim of this course is to introduce students to advanced topics in Human-Computer Interaction. In technical terms, it focuses on data visualisation and multimodal interaction. It also introduces other novel forms in interaction and evaluation, and legal and ethical issues around interactive and data-centred systems.',
        'year_in_university':4},
        {'name':'HUMAN-COMPUTER INTERACTION (SIT) SIT4045',
        'description':'The aim of this course is to introduce students to advanced topics in Human-Computer Interaction. It focuses on multimodal interaction, novel forms in interaction, users with different abilities and collaborative media.',
        'year_in_university':4},
        {'name':'INDIVIDUAL PROJECT (H) (COMBINED) COMPSCI4024P',
        'description':'The aim of the individual project is to allow students to undertake a substantial piece of individual work, involving planning, specification, design, execution, evaluation, presentation and report-writing.',
        'year_in_university':4},
        {'name':'INDIVIDUAL PROJECT (H) (SINGLE) COMPSCI4025P',
        'description':'The aim of the individual project is to allow students to undertake a substantial piece of individual work, involving planning, specification, design, execution, evaluation, presentation and report-writing.',
        'year_in_university':4,
        'views' : 7},
        {'name':'INDIVIDUAL PROJECT (SIT) SIT4027P',
        'description':'The aim of the individual project is to allow students to undertake a substantial piece of individual work, involving planning, specification, design, execution, evaluation, presentation and report-writing.',
        'year_in_university':4},
        {'name':'INFORMATION RETRIEVAL (H) COMPSCI4069',
        'description':'To present students with an in-depth examination of the theoretical and practical issues involved in providing tools to access large collections of documents, especially in the context of the World Wide Web.To present students with the practical engineering issues raised by the design and implementation of an information retrieval system.',
        'year_in_university':4},
        {'name':'INTERACTIVE SYSTEMS (H) COMPSCI4014',
        'description':'The aims of the course are: to offer students the opportunity to become familiar with one of the most important interaction paradigms; to enable students to become skilled in the use of techniques and tools for modelling, implementing and evaluating interactive systems; to enable students to apply the theories, techniques and tools presented in the course via challenging exercises which combine design, implementation and evaluation.',
        'year_in_university':4},
        {'name':'MACHINE LEARNING (H) COMPSCI4061',
        'description':'A practical introduction to the foundations of machine learning.',
        'year_in_university':4},
        {'name':'MOBILE HUMAN-COMPUTER INTERACTION (H) COMPSCI4068',
        'description':'Mobile Human-Computer Interaction (H) gives students an overview of the fields of mobile HCI and ubiquitous computing, and an understanding of the practical challenges associated with embedded software development for mobile interactive systems, and associated services.',
        'year_in_university':4},
        {'name':'MOBILE HUMAN-COMPUTER INTERACTION (SIT) SIT4047',
        'description':'Mobile Human-Computer Interaction (SIT) gives students an overview of the fields of mobile HCI and ubiquitous computing, and an understanding of the practical challenges associated with embedded software development for mobile interactive systems, and associated services.',
        'year_in_university':4},
        {'name':'MODELLING REACTIVE SYSTEMS (H) COMPSCI4031',
        'description':'Modelling concurrent, communicating systems using non-probabilistic and probabilistic techniques, and verification using the SPIN and PRISM model checkers.',
        'year_in_university':4},
        {'name':'NETWORKED SYSTEMS (H) COMPSCI4012',
        'description':'To introduce the fundamental concepts and theory of communications; To provide a solid understanding of the technologies that support modern networked computer systems; To introduce low-level network programming concepts, and give students practice with systems programming in C; To provide our students with the ability to evaluate and advise industry on the use and deployment of networked systems.',
        'year_in_university':4},
        {'name':'OPERATING SYSTEMS (H) COMPSCI4011',
        'description':'To introduce the students to the styles of coding required with an OS; To give a thorough presentation of the contents of a traditional OS, including the key abstractions; To show the range of algorithms and techniques available for specific OS problems, and the implications of selection specific algorithms for application behaviour; To develop an integrated understanding of what the computer is doing, from a non-naive view of hardware to the behaviour of multi-threaded application processes; present the alternatives and clarify the trade-offs that drive OS and hardware design.',
        'year_in_university':4},
        {'name':'PROFESSIONAL SKILLS AND ISSUES (H) COMPSCI4038',
        'description':'This course introduces the social, ethical, legal, and professional issues involved in the widespread deployment of information technology. It stimulates students to develop their own, well-argued positions on many of these issues.',
        'year_in_university':4},
        {'name':'PROFESSIONAL SOFTWARE DEVELOPMENT (H) COMPSCI4015',
        'description':'The aims of the course are to: Introduce students to modern software development methods and techniques for building and maintaining large systems; Prepare students to apply these methods and techniques presented to them in the context of an extended group-based software development exercise; Make the students aware of the professional, social and ethical dimensions of software development; Instil in the students a professional attitude towards software development.',
        'year_in_university':4},
        {'name':'PROGRAMMING COMPSCI4039',
        'description':'To provide a firm foundation in skills and key concepts essential for programming in Java, which is the main language used in the MSc IT programme; To provide a thorough introduction to problem solving and Java programming, giving a basis for study in topics such as algorithms and data structures, object-oriented design, and human computer interaction; To develop skills, required for implementing solutions to well-specified programming problems, which could then be transferred to other programming languages.',
        'year_in_university':4},
        {'name':'PROGRAMMING LANGUAGES (H) COMPSCI4016',
        'description':'This course aims to: Provide a conceptual framework that will enable students to understand familiar programming languages more deeply and learn new languages more efficiently; Show how the syntax of a programming language can be formalized; Explain the functions of compilers and interpreters, how they interact, and how they work; Show how to implement a compiler using compiler-generation tools.',
        'year_in_university':4},
        {'name':'PROGRAMMING AND SYSTEMS DEVELOPMENT (H) COMPSCI4084',
        'description':'Provides a short, intensive, hands-on introduction to the software and tools necessary for the MSc programmes in Computing Science: the Java and Python programming languages, associated tools, and the LINUX operating system.',
        'year_in_university':4},
        {'name':'RECOMMENDER SYSTEMS (H) COMPSCI4075',
        'description':'This course introduces the concepts, applications, algorithms, programming, and design of recommender systems -- software systems that recommend products or information, often based on extensive personalization. Recommender systems are widely used by many users on a day-to-day basis: while recommender systems have been pioneered by e-commerce sites such as Amazon and Netflix, they are widely used ranging in areas from marketing (e.g. personalized product recommendations with your supermarket loyalty card), education, social media, and financial services. This course discusses various techniques for making recommendations, including non-personalized, content-based, and collaborative recommendation techniques, and their evaluation.',
        'year_in_university':4},
        {'name':'ROBOTICS FOUNDATIONS (H) COMPSCI4076',
        'description':'This course will introduce students to the computational and mathematical concepts, information processing and software frameworks of robotic systems. It will also consider the sensory and actuation systems required by a robot to sense, understand and interact with its environment. The primary aim is to give students an understanding of how to prototype and implement autonomous robotic systems by making use of a sophisticated robotic middleware (e.g. Robot Operating System (ROS)), its associated data transmission channels, software robotic stacks and the underlying mathematics required to operate a robot. This is a hands-on course, designed to provide students with the required programming, mathematical and debugging skill-set to implement robotic solutions based on the use of off-the-shelf commercially available real and virtual robots. Python skills are a requirement for this course; C/C++ skills are desirable but not essential.',
        'year_in_university':4},
        {'name':'SAFETY CRITICAL SYSTEMS DEVELOPMENT (SIT) SIT4034',
        'description':'This course encourages students to apply engineering techniques to support the development of safety-critical applications. It also encourages students to consider the particular methodological and professional issues that surround the development of safety-critical systems.',
        'year_in_university':4,
        'views' : 8},
        {'name':'SAFETY-CRITICAL SYSTEMS DEVELOPMENT (H) COMPSCI4045',
        'description':'This course encourages students to apply engineering techniques to support the development of safety-critical applications. It also encourages students to consider the particular methodological and professional issues that surround the development of safety-critical systems.',
        'year_in_university':4},
        {'name':'SOFTWARE ENGINEERING FULL YEAR INDUSTRIAL PLACEMENT H COMPSCI4079',
        'description':'Software engineering students will undertake a full year assessed placement in industry to gain relevant practical experience.  Assessment materials engage students in the wider software engineering literature and encourage students to reflect on and share their experiences on placement.',
        'year_in_university':4},
        {'name':'SOFTWARE ENGINEERING SUMMER PLACEMENT (H) COMPSCI4046',
        'description':'During the long vacation between third and fourth year, Software Engineering students will normally be required to undertake a summer placement of at least 10 weeks to gain relevant practical experience.',
        'year_in_university':4},
        {'name':'SYSTEMS AND NETWORKS COMPSCI4043',
        'description':'To introduce the structure and function of computer systems, in particular: To introduce the concept of representation of data; To provide a general understanding of what computers are and how they work; To provide background helpful for better understanding the behaviour of programming languages, compilers, and operating systems; To convey understanding of descriptions of computer systems and projections of future trends.',
        'year_in_university':4},
        {'name':'SYSTEMS PROGRAMMING (H) COMPSCI4081',
        'description':'This course aims to introduce students to low-level systems programming. It focusses on programming in an unmanaged environment, where data layout matters, and where performance is critical. This might include operating systems kernels, device drivers, low-level networking code, or other areas where the software-machine interface becomes critical. The course will use a low-level systems programming language, for example C, to introduce these concepts. Students will be expected to learn the basics of this language in a self-study manner prior to entry, however a review of the major concepts will be provided at the start of the course. This material is an essential prerequisite for the Operating Systems (H) and Networked Systems (H) courses.',
        'year_in_university':4},
        {'name':'TEAM PROJECT (H) COMPSCI4047',
        'description':'This course gives students the experience of working on a substantial team based software project. The course provides the opportunity to apply the principles, practices and tools learned during the associated Professional Software Development (H) course.',
        'year_in_university':4},
        {'name':'TEAM PROJECT ESE (H) COMPSCI4044',
        'description':'This course gives students the experience of working on a substantial team based software project. The course provides the opportunity to apply the principles, practices and tools learned during the associated Professional Software Development (H) course.',
        'year_in_university':4},
        {'name':'TEAM PROJECT MINOR (H) COMPSCI4070',
        'description':'This course gives students the experience of working on a substantial team based software project. The course provides the opportunity to apply the principles, practices and tools learned during the associated Professional Software Development (H) course.',
        'year_in_university':4},
        {'name':'TEXT AS DATA - AN INTRODUCTION TO DOCUMENT ANALYTICS (H) COMPSCI4074',
        'description':'This course will introduce stochastic notions necessary for analysing text/documents, in both unsupervised and supervised approaches. The course is designed to be applied in nature, using various text analytics examples, and introducing students to various toolkits for document processing (e.g. Weka/Spark Mlib).',
        'year_in_university':4},
        {'name':'THEORY OF COMPUTATION (H) COMPSCI4072',
        'description':'This course covers the theory of sequential, concurrent and quantum computation. The main topics are: formal language theory and the connection to automata; lambda calculus as a foundation for functional computation; pi calculus as a foundation for concurrent computation; the theory of operational semantics and type systems; principles of quantum computation.',
        'year_in_university':4},
        {'name':'WEB SCIENCE (H) COMPSCI4077',
        'description':'Web Science is the study of the World Wide Web (WWW), its components, facets and characteristics and the impact it has on both society and technology. The World Wide Web changed the way in which we create information, communicate and interact. New models of social networks (LinkedIn, Facebook, etc.) create opportunities, which were not available before. Exploiting such data and networks for the benefit of individuals and organizations has become a key in our knowledge society.',
        'year_in_university':4},
        {'name':'WEB SCIENCE (SIT) SIT4053',
        'description':'Web Science is the study of the World Wide Web (WWW), its components, facets and characteristics and the impact it has on both society and technology. The World Wide Web changed the way in which we create information, communicate and interact. New models of social networks (LinkedIn, Facebook, etc.) create opportunities, which were not available before. Exploiting such data and networks for the benefit of individuals and organizations has become a key in our knowledge society.',
        'year_in_university':4}
    ]
    postgraduate_courses = [
        {'name':'ADVANCED PROGRAMMING (M) COMPSCI5002',
        'description':'The course is intended to extend the students knowledge to encompass a number of important programming techniques necessary for building a modern computing application. The course content will include techniques in Java to deal with a range of issues drawn from the following: program design using an object oriented programming model; modelling data using programming language type systems; event and exception programming; providing a graphical user interface; thread programming; persistence; and distributed programming. It will also cover in brief the underlying Java run time system and techniques found in other languages.',
        'year_in_university':5},
        {'name':'ADVANCED SYSTEMS PROGRAMMING (M) COMPSCI5083',
        'description':'This course covers advanced topics systems programming, building on the material in Systems Programming (H) to explore new techniques for safer and more effective systems programming. It will focus on programming in an unmanaged environment, where data layout matters, and where performance is critical. This might include operating systems kernels, device drivers, low-level networking code, or other areas where the software-machine interface becomes critical.',
        'year_in_university':5},
        {'name':'ALGORITHMS AND DATA STRUCTURES (M) COMPSCI5004',
        'description':'To study the concept of algorithms, and how to analyse their efficiency; To study the concept of abstract data types, and the abstract data types most commonly used in software development; To study the basic data structures most commonly used to represent these abstract data types, together with algorithms operating on these data structures.',
        'year_in_university':5},
        {'name':'ARTIFICIAL INTELLIGENCE (M) COMPSCI5087',
        'description':'Artificial Intelligence (M) is an introduction to Artificial Intelligence, giving the students an overview of intelligent agent design. ',
        'year_in_university':5},
        {'name':'BIG DATA: SYSTEMS, PROGRAMMING, AND MANAGEMENT (M) COMPSCI5088',
        'description':'Big Data is nowadays manifested in a very large number of environments and application fields pertaining to our education, entertainment, health, public governance, enterprising, etc. The course will endow students with the understanding of the new challenges big data introduces and the currently available solutions. These include (i) challenges pertaining to the modelling, accessing, and storing of big data, (ii) an understanding of the fundamentals of systems designed to store and access big data, and (iii) programming paradigms for efficient scalable access to big data.',
        'year_in_university':5},
        {'name':'COMPUTATIONAL SOCIAL INTELLIGENCE (M) COMPSCI5095',
        'description':'The course introduces the core methodologies behind automatic approaches aimed at making sense of social and psychological aspects of human behaviour. In particular, the course shows 1) how to design and organise the observation of human behaviour in view of the application of automatic approaches, 2) how to apply psychometric instruments for the quantitative analysis of social and psychological phenomena, and 3) how to apply basic statistical techniques to human behaviour analysis and understanding. The course is interdisciplinary and it requires the acquisition of both computing and social psychological notions. The application areas to which the course is relevant include, e.g., social robotics, user experience analysis, social media analytics, surveillance and e-health (the list is not exhaustive).',
        'year_in_university':5},
        {'name':'CONSTRAINT PROGRAMMING (M) COMPSCI5006',
        'description':'We cover Constraint Programming and its use in solving a number of combinatorial problems. We also cover the underlying technology.',
        'year_in_university':5},
        {'name':'CONVERSATIONAL INTERFACES (M) COMPSCI5094',
        'description':'This course provides a hands-on introduction to conversational interaction. Students will learn about the components involved in a conversational system, the techniques for implementing such a system, and how conversational systems are evaluated. Various forms of conversational interface will be covered, including chatbots, spoken dialogue systems, multimodal dialogue systems, and social robots. During the course, students will implement and evaluate a conversational interactive system.',
        'year_in_university':5},
        {'name':'CRYPTOGRAPHY AND SECURE DEVELOPMENT (M) COMPSCI5079',
        'description':'A course on cryptographic algorithms and how to develop code for secure systems.',
        'year_in_university':5},
        {'name':'CYBER SECURITY FUNDAMENTALS (M) COMPSCI5063',
        'description':'This course provides an introduction to the foundational aspects of computer security, such as algorithms and protocols. It also covers ways in which these systems can be attacked and techniques for thwarting these attacks.',
        'year_in_university':5},
        {'name':'CYBER SYSTEM FORENSICS (M) COMPSCI5080',
        'description':'The course will enable the acquisition of analytical, scientific and communication skills to investigate cyber security incidents and present appropriate evidence to a non-technical audience. The course will expect students to comprehend aspects of forensic investigation and to present findings to non-technical stakeholders, e.g. court-room.',
        'year_in_university':5},
        {'name':'DATABASE THEORY AND APPLICATION (M) COMPSCI5076',
        'description':'The aim of this course is to introduce students to the concepts of information management by way of databases, including relational databases, relational algebra, functional dependency theories, and other data management and analytics solutions. The course will provide students with the opportunity to develop skills which will assist them to manage information in the current digital age.',
        'year_in_university':5},
        {'name':'DEEP LEARNING (M) COMPSCI5085',
        'description':'This course is the next step beyond our introductory machine learning course and teaches students about modern techniques for machine learning with high-dimensional image and sequence (time-series) data, and the underlying computational structures for such systems.',
        'year_in_university':5},
        {'name':'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084',
        'description':'This course aims to develop in students a better understanding of the computing science challenges posed by the dominant highly concurrent architectures. These include engineering scalable and reliable systems. Students will gain both a broad overview of emerging technologies for engineering reliable and scalable systems, together with practical experience using a small number of key technologies for designing, implementing and evaluating scalable parallel systems and reliable distributed systems.',
        'year_in_university':5},
        {'name':'ENTERPRISE CYBER SECURITY (M) COMPSCI5077',
        'description':'This course will focus on cyber security management within an organisation. It will ensure that students will know how to satisfy legislation related to securing personal and sensitive information and how to manage data correctly.',
        'year_in_university':5},
        {'name':'HUMAN COMPUTER INTERACTION DESIGN AND EVALUATION (M) COMPSCI5057',
        'description':'The course will focus on two aspects of HCI: user centred software design, and interface evaluation methods. Both will be useful for students when they do their MSc projects.',
        'year_in_university':5},
        {'name':'HUMAN-CENTRED SECURITY (M) COMPSCI5060',
        'description':'This course teaches you the design and evaluation of usable, secure and privacy aware systems.',
        'year_in_university':5},
        {'name':'INFORMATION RETRIEVAL (M) COMPSCI5011',
        'description':'To present students with an in-depth examination of the theoretical and practical issues involved in providing tools to access large collections of documents, especially in the context of the World Wide Web. To present students with the practical engineering issues raised by the design and implementation of an information retrieval system.',
        'year_in_university':5},
        {'name':'INTERNET TECHNOLOGY (M) COMPSCI5012',
        'description':'The aim of this course is to provide students with a comprehensive overview of web application development. It will provide students with the skills to design and develop distributed web applications in a disciplined manner, using a range of tools and technologies. It will also strengthen their understanding of the context and rationale of distributed systems.',
        'year_in_university':5},
        {'name':'INTRODUCTION TO DATA SCIENCE AND SYSTEMS (M) COMPSCI5089',
        'description':'To give students a grounding in foundational elements of data science theory and systems, including Data transformations, Database Systems, and practical data processing pipelines.',
        'year_in_university':5},
        {'name':'MSC IT+ TEAM PROJECT (M) COMPSCI5074',
        'description':'Students undertake a suitable development project that extends their programming skills while integrating relevant skills from their database and software project management courses.',
        'year_in_university':5},
        {'name':'MSC PROJECT FOR COMPUTING SCIENCE (SOCIAL) COMPSCI5098P',
        'description':'This course is intended for students registered on the four year training programme - PhD with Integrated Study in Computing Science and Psychology - as part of an early exit award only.The aim of the project is to enable students to carry out a substantial, independent, individual project at level M. It will entail the development of a software product and/or the conduct of a research project. Students will submit a dissertation for assessment.',
        'year_in_university':5},
        {'name':'MSC PROJECT FOR COMPUTING SCIENCE+ COMPSCI5086P',
        'description':'The aim of the project is to enable students to carry out a substantial, independent, individual project at level M. It will entail the development of a software product and/or the conduct of a research project. Students will submit a dissertation for assessment.',
        'year_in_university':5},
        {'name':'MSC PROJECT FOR INFORMATION TECHNOLOGY + COMPSCI5018P',
        'description':'The aim of the project is to enable students to carry out a substantial, independent, individual project at level M. It will entail the development of a software product and/or the conduct of a research project. Students will submit a dissertation for assessment. ',
        'year_in_university':5},
        {'name':'MSCI (SANDWICH YEAR) SOFTWARE ENGINEERING INDIVIDUAL PROJECT COMPSCI5082P',
        'description':'The course provides students with the opportunity to conduct an independent, individual Software Engineering research project at level M.  Students undertake a literature survey to formally identify a research problem and then carry out an investigation and write up the results.',
        'year_in_university':5},
        {'name':'MSCI RESEARCH PROPOSAL AND PROJECT COMPSCI5073P',
        'description':'The aim of this course to enable students to prepare and undertake a substantial, independent, individual research-oriented project at level M. It will include a literature survey, indentifying and refining a research problem in Computing Science, then carrying out an investigation of the problem and writing up the results.',
        'year_in_university':5},
        {'name':'MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
        'description':'The aim of this course to enable students to prepare and undertake a substantial, independent, individual research-oriented project at level M. It will include a literature survey, indentifying and refining a research problem in Computing Science, then carrying out an investigation of the problem and writing up the results.',
        'year_in_university':5},
        {'name':'MACHINE LEARNING FOR DATA SCIENTISTS (M) COMPSCI5090',
        'description':'A practical introduction to the foundations of machine learning, based around a series of case studies using data from a range of research areas. ',
        'year_in_university':5},
        {'name':'MOBILE HUMAN-COMPUTER INTERACTION (M) COMPSCI5015',
        'description':'Mobile Human-Computer Interaction (M) gives students an overview of the fields of mobile HCI and ubiquitous computing, and an understanding of the practical challenges associated with embedded software development for mobile interactive systems, and associated services.',
        'year_in_university':5},
        {'name':'MODELLING REACTIVE SYSTEMS (M) COMPSCI5075',
        'description':'Modelling concurrent, communicating systems using non-probabilistic and probabilistic techniques, and verification using the SPIN and PRISM model checkers.',
        'year_in_university':5},
        {'name':'PROGRAMMING FOR ARTIFICIAL INTELLIGENCE (M) COMPSCI5097',
        'description':'The course provides the students with basic programming skills through the development of simple machine intelligence approaches. After an introduction to the main concepts underlying machine learning (e.g., supervised and unsupervised learning, etc.) and signal processing (time domain measurements, convolution, etc.), the students will be guided through the development of algorithms capable to extract information from data.',
        'year_in_university':5},
        {'name':'PROJECT RESEARCH READINGS IN COMPUTING SCIENCE (M) COMPSCI5003',
        'description':'Immerse students in research topics in a specialist area of Computing Science; Reinforce critical reading and reviewing skills learned in the Research Methods and Techniques course; Enable students to develop their critical thinking and group discussion capabilities; Develop students presentation skills.',
        'year_in_university':5},
        {'name':'RECOMMENDER SYSTEMS (M) COMPSCI5091',
        'description':'This course introduces the concepts, applications, algorithms, programming, and design of recommender systems -- software systems that recommend products or information, often based on extensive personalization. Recommender systems are widely used by many users on a day-to-day basis: while recommender systems have been pioneered by e-commerce sites such as Amazon and Netflix, they are widely used ranging in areas from marketing (e.g. personalized product recommendations with your supermarket loyalty card), education, social media, and financial services. This course discusses various techniques for making recommendations, including non-personalized, content-based, and collaborative recommendation techniques, and their evaluation.',
        'year_in_university':5},
        {'name':'RESEARCH METHODS AND TECHNIQUES (M) FOR MSCI COMPSCI5025',
        'description':'This course covers the fundamental principles, of the scientific method. Students will learn the core skills of planning, designing, executing, evaluating and presenting research.',
        'year_in_university':5},
        {'name':'RESEARCH AND PROFESSIONAL SKILLS (M) COMPSCI5092',
        'description':'This course covers the fundamental principles of the scientific method, and the core skills of planning, designing, executing, evaluating and presenting research. In addition, it introduces the social, ethical, legal, and professional issues involved in the widespread deployment of information technology.',
        'year_in_university':5},
        {'name':'SAFETY-CRITICAL SYSTEMS DEVELOPMENT (M) COMPSCI5068',
        'description':'This course encourages students to apply engineering techniques to support the development of safety-critical applications. It also encourages students to consider the particular methodological and professional issues that surround the development of safety-critical systems.  It provides an overview of recent research into software certification, into national critical infrastructure protection and to the interactions between safety and cyber-security.',
        'year_in_university':5},
        {'name':'SECURED SOFTWARE ENGINEERING (M) COMPSCI5093',
        'description':'This course covers secure software engineering methods and techniques. It explores all aspects of the software engineering lifecycle that are directly applicable to designing systems where security and/or privacy is critical. ',
        'year_in_university':5},
        {'name':'SOFTWARE ENGINEERING (M) COMPSCI5059',
        'description':'To introduce the basic concepts in software engineering; To present methods for the design, implementation, testing and documentation of object-oriented programs; To develop program comprehension and design skills by studying and extending existing programs. To introduce different approaches to software project management, and a variety of tools are available to support effective management of software development projects. To introduce economic, legal, social, ethical and environmental, and professional issues involved in the widespread deployment of information technology.',
        'year_in_university':5},
        {'name':'TEXT AS DATA - AN INTRODUCTION TO DOCUMENT ANALYTICS (M) COMPSCI5096',
        'description':'This course will introduce stochastic notions necessary for analysing text/documents, in both unsupervised and supervised approaches. The course is designed to be applied in nature, using various text analytics examples, and introducing students to various toolkits for document processing (e.g. scikit-learn, spaCy, NLTK).',
        'year_in_university':5},
        {'name':'WEB SCIENCE (M) COMPSCI5078',
        'description':'Web Science is the study of the World Wide Web (WWW), its components, facets and characteristics and the impact it has on both society and technology. The World Wide Web changed the way in which we create information, communicate and interact. New models of social networks (LinkedIn, Facebook, etc.) create opportunities, which were not available before. Exploiting such data and networks for the benefit of individuals and organizations has become a key in our knowledge society.',
        'year_in_university':5}
    ]
    year1_students = [
        {'username':'Arthur',
         'password':'pass',
         'firstName':'Arthur',
         'lastName':'Tull',
         'email':'ArthurMTull@rhyta.com',
         'currentStudent':True,
         'yearStudying':1,
         'courses':['1CT INTRODUCTION TO COMPUTATIONAL THINKING COMPSCI1016',
                    '1S SYSTEMS COMPSCI1018',
                    '1F - COMPUTING FUNDAMENTALS COMPSCI1006',
                    'COMPUTING SCIENCE 1PX (ALTERNATE ROUTE) COMPSCI1017',
                    'SPATIAL SKILLS TRAINING 1 COMPSCI1026'],
         'contact':True},
        {'username':'Melvin',
         'password':'pass',
         'firstName':'Melvin',
         'lastName':'Booker',
         'email':'MelvinPBooker@teleworm.us',
         'currentStudent':True,
         'yearStudying':1,
         'courses':['1S SYSTEMS COMPSCI1018',
                    '1F - COMPUTING FUNDAMENTALS COMPSCI1006',
                    'COMPUTING SCIENCE 1P (STANDARD ROUTE) COMPSCI1001',
                    'HOW TO LEARN A NEW LANGUAGE COMPSCI1020',
                    'PRACTICAL ALGORITHMS COMPSCI1021',
                    'SPATIAL SKILLS TRAINING 1 COMPSCI1026',
                    'TESTING AND SOFTWARE IMPROVEMENT COMPSCI1022',
                    'WORKPLACE ASSESSMENT YEAR 1 COMPSCI1024'],
         'contact':False},
        {'username':'James',
         'password':'pass',
         'firstName':'James',
         'lastName':'Morris',
         'email':'JamesGMorris@rhyta.com',
         'currentStudent':True,
         'yearStudying':1,
         'courses':['1CT INTRODUCTION TO COMPUTATIONAL THINKING COMPSCI1016',
                    '1S SYSTEMS COMPSCI1018',
                    '1F - COMPUTING FUNDAMENTALS COMPSCI1006',
                    'COMPUTING SCIENCE 1PX (ALTERNATE ROUTE) COMPSCI1017',
                    'FOUNDATIONS OF PROFESSIONAL SOFTWARE ENGINEERING COMPSCI1019',
                    'WEB APPLICATION SYSTEMS COMPSCI1023',
                    'WORKPLACE ASSESSMENT YEAR 1 COMPSCI1024'],
         'contact':False},
        {'username':'Mary',
         'password':'pass',
         'firstName':'Mary',
         'lastName':'Dees',
         'email':'MaryJDees@dayrep.com',
         'currentStudent':True,
         'yearStudying':1,
         'courses':['1S SYSTEMS COMPSCI1018',
                    '1F - COMPUTING FUNDAMENTALS COMPSCI1006',
                    'COMPUTING SCIENCE 1P (HALF COURSE) COMPSCI1005',
                    'FOUNDATIONS OF PROFESSIONAL SOFTWARE ENGINEERING COMPSCI1019',
                    'PRACTICAL ALGORITHMS COMPSCI1021',
                    'TESTING AND SOFTWARE IMPROVEMENT COMPSCI1022',
                    'WEB APPLICATION SYSTEMS COMPSCI1023'],
         'contact':True},
        {'username':'Bret',
         'password':'pass',
         'firstName':'Bret',
         'lastName':'Woolfolk',
         'email':'BretFWoolfolk@teleworm.us',
         'currentStudent':True,
         'yearStudying':1,
         'courses':['COMPUTING SCIENCE 1P (HALF COURSE) COMPSCI1005',
                    'FOUNDATIONS OF PROFESSIONAL SOFTWARE ENGINEERING COMPSCI1019',
                    'HOW TO LEARN A NEW LANGUAGE COMPSCI1020',
                    'PRACTICAL ALGORITHMS COMPSCI1021',
                    'SPATIAL SKILLS TRAINING 1 COMPSCI1026',
                    'TESTING AND SOFTWARE IMPROVEMENT COMPSCI1022',
                    'WEB APPLICATION SYSTEMS COMPSCI1023',
                    'WORKPLACE ASSESSMENT YEAR 1 COMPSCI1024'],
         'contact':True}, 
    ]
    year2_students = [
        {'username':'Ada',
         'password':'pass',
         'firstName':'Ada',
         'lastName':'Sartain',
         'email':'AdaMSartain@teleworm.us',
         'currentStudent':True,
         'yearStudying':2,
         'courses':['ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
                    'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
                    'JAVA PROGRAMMING 2 COMPSCI2001',
                    'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
                    'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
                    'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021'],
         'contact':True},
        {'username':'Henry',
         'password':'pass',
         'firstName':'Henry',
         'lastName':'Flannigan',
         'email':'HenryTFlannigan@teleworm.us',
         'currentStudent':True,
         'yearStudying':2,
         'courses':['ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
                    'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
                    'JAVA PROGRAMMING 2 COMPSCI2001',
                    'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
                    'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
                    'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021'],
         'contact':False},
        {'username':'Antwan',
         'password':'pass',
         'firstName':'Antwan',
         'lastName':'Pool',
         'email':'AntwanEPool@armyspy.com',
         'currentStudent':True,
         'yearStudying':2,
         'courses':['ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
                    'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
                    'JAVA PROGRAMMING 2 COMPSCI2001',
                    'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
                    'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
                    'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021'],
         'contact':False},
        {'username':'MelvinM',
         'password':'pass',
         'firstName':'Melvin',
         'lastName':'Cox',
         'email':'MelvinMCox@dayrep.com',
         'currentStudent':True,
         'yearStudying':2,
         'courses':['ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
                    'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
                    'JAVA PROGRAMMING 2 COMPSCI2001',
                    'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
                    'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
                    'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021'],
         'contact':True},
        {'username':'Heather',
         'password':'pass',
         'firstName':'Heather',
         'lastName':'Barron',
         'email':'HeatherRBarron@dayrep.com',
         'currentStudent':True,
         'yearStudying':2,
         'courses':['ALGORITHMIC FOUNDATIONS 2 COMPSCI2003',
                    'ALGORITHMS & DATA STRUCTURES 2 COMPSCI2007',
                    'JAVA PROGRAMMING 2 COMPSCI2001',
                    'NETWORKS AND OPERATING SYSTEMS ESSENTIALS 2 COMPSCI2024',
                    'OBJECT-ORIENTED SOFTWARE ENGINEERING 2 COMPSCI2008',
                    'WEB APPLICATION DEVELOPMENT 2 COMPSCI2021'],
         'contact':False},
    ]
    year3_students = [
        {'username':'George',
         'password':'pass',
         'firstName':'George',
         'lastName':'Johnson',
         'email':'GeorgeNJohnson@rhyta.com',
         'currentStudent':True,
         'yearStudying':3,
         'courses':['SOFTWARE ENGINEERING M3 COMPSCI3005',
                    'TEAM PROJECT 3 COMPSCI3004'],
         'contact':True},
        {'username':'Robert',
         'password':'pass',
         'firstName':'Robert',
         'lastName':'Mumford',
         'email':'RobertBMumford@jourrapide.com',
         'currentStudent':True,
         'yearStudying':3,
         'courses':['SOFTWARE ENGINEERING M3 COMPSCI3005',
                    'TEAM PROJECT 3 COMPSCI3004'],
         'contact':False},
        {'username':'Madeline',
         'password':'pass',
         'firstName':'Madeline',
         'lastName':'Karsten',
         'email':'MadelineTKarsten@rhyta.com',
         'currentStudent':True,
         'yearStudying':3,
         'courses':['SOFTWARE ENGINEERING M3 COMPSCI3005',
                    'TEAM PROJECT 3 COMPSCI3004'],
         'contact':True},
        {'username':'Martha',
         'password':'pass',
         'firstName':'Martha',
         'lastName':'Mattingly',
         'email':'MarthaTMattingly@armyspy.com',
         'currentStudent':True,
         'yearStudying':3,
         'courses':['SOFTWARE ENGINEERING M3 COMPSCI3005',
                    'TEAM PROJECT 3 COMPSCI3004'],
         'contact':False},
        {'username':'Oleta',
         'password':'pass',
         'firstName':'Oleta',
         'lastName':'Logue',
         'email':'OletaGLogue@dayrep.com',
         'currentStudent':True,
         'yearStudying':3,
         'courses':['SOFTWARE ENGINEERING M3 COMPSCI3005',
                    'TEAM PROJECT 3 COMPSCI3004'],
         'contact':False},
    ]
    year4_students = [
        {'username':'Tom',
         'password':'pass',
         'firstName':'Tom',
         'lastName':'Dixon',
         'email':'TomCDixon@teleworm.us',
         'currentStudent':True,
         'yearStudying':4,
         'courses':['ADVANCED SOFTWARE ENGINEERING PRACTICES (H) COMPSCI4071',
                    'ARTIFICIAL INTELLIGENCE (H) COMPSCI4004',
                    'SAFETY-CRITICAL SYSTEMS DEVELOPMENT (H) COMPSCI4045',
                    'TEAM PROJECT ESE (H) COMPSCI4044',
                    'OPERATING SYSTEMS (H) COMPSCI4011',
                    'RECOMMENDER SYSTEMS (H) COMPSCI4075',
                    'WEB SCIENCE (SIT) SIT4053',
                    'PROGRAMMING COMPSCI4039'],
         'contact':True},
        {'username':'Kerry',
         'password':'pass',
         'firstName':'Kerry',
         'lastName':'Lesniak',
         'email':'KerryTLesniak@rhyta.com',
         'currentStudent':True,
         'yearStudying':4,
         'courses':['ADVANCED SOFTWARE ENGINEERING PRACTICES (H) COMPSCI4071',
                    'ARTIFICIAL INTELLIGENCE (H) COMPSCI4004',
                    'SAFETY-CRITICAL SYSTEMS DEVELOPMENT (H) COMPSCI4045',
                    'WEB SCIENCE (SIT) SIT4053',
                    'PROGRAMMING COMPSCI4039'],
         'contact':False},
        {'username':'DavidB',
         'password':'pass',
         'firstName':'David',
         'lastName':'Morgan',
         'email':'DavidBMorgan@rhyta.com',
         'currentStudent':True,
         'yearStudying':4,
         'courses':['SAFETY-CRITICAL SYSTEMS DEVELOPMENT (H) COMPSCI4045',
                    'TEAM PROJECT ESE (H) COMPSCI4044',
                    'OPERATING SYSTEMS (H) COMPSCI4011',
                    'RECOMMENDER SYSTEMS (H) COMPSCI4075',
                    'WEB SCIENCE (SIT) SIT4053',
                    'PROGRAMMING COMPSCI4039'],
         'contact':True},
        {'username':'JamesB',
         'password':'pass',
         'firstName':'James',
         'lastName':'Simpson',
         'email':'JamesBSimpson@rhyta.com',
         'currentStudent':True,
         'yearStudying':4,
         'courses':['ARTIFICIAL INTELLIGENCE (H) COMPSCI4004',
                    'TEAM PROJECT ESE (H) COMPSCI4044',
                    'OPERATING SYSTEMS (H) COMPSCI4011',
                    'WEB SCIENCE (SIT) SIT4053',
                    'PROGRAMMING COMPSCI4039'],
         'contact':True},
        {'username':'WillieH',
         'password':'pass',
         'firstName':'Willie',
         'lastName':'McReynolds',
         'email':'WillieHMcReynolds@dayrep.com',
         'currentStudent':True,
         'yearStudying':4,
         'courses':['ADVANCED SOFTWARE ENGINEERING PRACTICES (H) COMPSCI4071',
                    'ARTIFICIAL INTELLIGENCE (H) COMPSCI4004',
                    'SAFETY-CRITICAL SYSTEMS DEVELOPMENT (H) COMPSCI4045',
                    'TEAM PROJECT ESE (H) COMPSCI4044',
                    'OPERATING SYSTEMS (H) COMPSCI4011',
                    'RECOMMENDER SYSTEMS (H) COMPSCI4075',
                    'WEB SCIENCE (SIT) SIT4053',
                    'PROGRAMMING COMPSCI4039'],
         'contact':False},
    ]
    year5_students = [
        {'username':'BrunaC',
         'password':'pass',
         'firstName':'Bruna',
         'lastName':'Torres',
         'email':'BrunaCTorres@jourrapide.com',
         'currentStudent':True,
         'yearStudying':5,
         'courses':['ARTIFICIAL INTELLIGENCE (M) COMPSCI5087',
                    'MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
                    'MOBILE HUMAN-COMPUTER INTERACTION (M) COMPSCI5015',
                    'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084'],
         'contact':False},
        {'username':'AnnieP',
         'password':'pass',
         'firstName':'Annie',
         'lastName':'Palmer',
         'email':'AnniePPalmer@rhyta.com',
         'currentStudent':True,
         'yearStudying':5,
         'courses':['ARTIFICIAL INTELLIGENCE (M) COMPSCI5087',
                    'MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
                    'HUMAN-CENTRED SECURITY (M) COMPSCI5060',
                    'ADVANCED SYSTEMS PROGRAMMING (M) COMPSCI5083',
                    'MACHINE LEARNING FOR DATA SCIENTISTS (M) COMPSCI5090',
                    'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084'],
         'contact':True},
        {'username':'GaryS',
         'password':'pass',
         'firstName':'Gary',
         'lastName':'Hackler',
         'email':'GarySHackler@teleworm.us',
         'currentStudent':True,
         'yearStudying':5,
         'courses':['MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
                    'HUMAN-CENTRED SECURITY (M) COMPSCI5060',
                    'ADVANCED SYSTEMS PROGRAMMING (M) COMPSCI5083',
                    'MACHINE LEARNING FOR DATA SCIENTISTS (M) COMPSCI5090',
                    'SOFTWARE ENGINEERING (M) COMPSCI5059',
                    'MOBILE HUMAN-COMPUTER INTERACTION (M) COMPSCI5015',
                    'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084'],
         'contact':False},
        {'username':'HollyK',
         'password':'pass',
         'firstName':'Holly',
         'lastName':'Stewart',
         'email':'HollyKStewart@teleworm.us',
         'currentStudent':True,
         'yearStudying':5,
         'courses':['MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
                    'HUMAN-CENTRED SECURITY (M) COMPSCI5060',
                    'SOFTWARE ENGINEERING (M) COMPSCI5059',
                    'MOBILE HUMAN-COMPUTER INTERACTION (M) COMPSCI5015',
                    'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084'],
         'contact':True},
        {'username':'EdwinO',
         'password':'pass',
         'firstName':'Edwin',
         'lastName':'Bow',
         'email':'EdwinOBow@teleworm.us',
         'currentStudent':True,
         'yearStudying':5,
         'courses':['MSCI RESEARCH PROPOSAL AND PROJECT (HALF) COMPSCI5072P',
                    'HUMAN-CENTRED SECURITY (M) COMPSCI5060',
                    'ADVANCED SYSTEMS PROGRAMMING (M) COMPSCI5083',
                    'MACHINE LEARNING FOR DATA SCIENTISTS (M) COMPSCI5090',
                    'SOFTWARE ENGINEERING (M) COMPSCI5059',
                    'MOBILE HUMAN-COMPUTER INTERACTION (M) COMPSCI5015',
                    'DISTRIBUTED AND PARALLEL TECHNOLOGIES (M) COMPSCI5084'],
         'contact':True},
    ]
    
    non_students = [
        {'username':'GertrudeR',
         'password':'pass',
         'firstName':'Gertrude',
         'lastName':'Turner',
         'email':'GertrudeRTurner@jourrapide.com',
         'currentStudent':False},
        {'username':'RubenA',
         'password':'pass',
         'firstName':'Ruben',
         'lastName':'Hanson',
         'email':'RubenAHanson@rhyta.com',
         'currentStudent':False},
        {'username':'DavidW',
         'password':'pass',
         'firstName':'David',
         'lastName':'Milton',
         'email':'DavidWMilton@dayrep.com',
         'currentStudent':False},
        {'username':'JamesN',
         'password':'pass',
         'firstName':'James',
         'lastName':'Beck',
         'email':'JamesNBeck@armyspy.com',
         'currentStudent':False},
        {'username':'CharlesS',
         'password':'pass',
         'firstName':'Charles',
         'lastName':'Harding',
         'email':'CharlesSHarding@rhyta.com',
         'currentStudent':False},
    ]
        
    all_courses = [undergraduate_1year_courses,undergraduate_2year_courses,undergraduate_3year_courses,undergraduate_4year_courses,postgraduate_courses]
    example_users = [year1_students, year2_students, year3_students, year4_students, year5_students, non_students]

    # The code below goes through the all_courses list, then for each sublist, adds the courses.
    for cat in all_courses:
        for course in cat:
            if 'views' in course.keys():
                add_course(course['name'], course['description'], course['year_in_university'], course['views'] )
            else:
                add_course(course['name'], course['description'], course['year_in_university'])
            
    # Print out the courses we have added.
    for c in Course.objects.all():
            print(f'{c}')

    # The code below goes through the example_users list, then for each sublist, creates the user and user profile.
    for category in example_users:
        if category == non_students:
            for user in category:
                add_non_student(user['username'], user['password'], user['firstName'], user['lastName'], user['email'], user['currentStudent'])
        else:
            for user in category:
                add_student(user['username'], user['password'], user['firstName'], user['lastName'], user['email'], user['currentStudent'], user['yearStudying'], user['courses'], user['contact'])

    # Print out the user profiles we have added.
    for userProfile in UserProfile.objects.all():
        print(f'{userProfile}')
    

def add_course(name, description, year_in_university,views=0):
    c = Course.objects.get_or_create(name=name)[0]
    c.description=description
    c.year_in_university=year_in_university
    c.views=views
    c.save()
    return c

def add_student(username, password, firstName, lastName, email, currentStudent, yearStudying, courses, contact):
    userObject = User.objects.get_or_create(username=username)[0]
    userObject.set_password(password)
    userObject.save()
     
    userProfile = UserProfile.objects.get_or_create(user=userObject)[0]
    userProfile.first_name = firstName
    userProfile.last_name = lastName
    userProfile.email = email
    userProfile.current_student = currentStudent
    userProfile.year_of_studies = yearStudying

    for course in courses:
        courseObject = Course.objects.get(name = course)
        userProfile.courses.add(courseObject)
            
    userProfile.contact = contact
    userProfile.save()
    return userProfile

def add_non_student(username, password, firstName, lastName, email, currentStudent):
    userObject = User.objects.get_or_create(username=username)[0]
    userObject.set_password(password)
    userObject.save()
     
    userProfile = UserProfile.objects.get_or_create(user=userObject)[0]
    userProfile.first_name = firstName
    userProfile.last_name = lastName
    userProfile.email = email
    userProfile.current_student = currentStudent
    
    userProfile.save()
    return userProfile
    
# Start execution here!
if __name__ == '__main__':
    print('Starting CSapp population script...')
    populate()
